version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "15:00"
      timezone: "Europe/Vilnius"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action*"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "11:00"
      timezone: "Europe/Vilnius"
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Vilnius"
    cooldown:
      default-days: 7
