---
version: 2

builds:
  - binary: external-dns-poweradmin-webhook
    main: ./cmd/webhook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'main.Version={{ .Tag }}'

archives:
  - id: archive
    name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz

source:
  enabled: true

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - --yes
      - "--output-certificate=${certificate}"
      - "--bundle=${signature}"
      - "${artifact}"
    artifacts: checksum
    output: true

sboms:
  - artifacts: archive

dockers_v2:
  - dockerfile: Dockerfile.goreleaser
    images:
      - "ghcr.io/poweradmin/external-dns-poweradmin-webhook"
      - "docker.io/poweradmin/external-dns-poweradmin-webhook"
    tags:
      - "{{ .Tag }}"
      - latest
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: manifests
    output: true
    args:
      - sign
      - --yes
      - "${artifact}"

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: "^.*feat.*:.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix.*:.*$"
      order: 1
    - title: Other
      order: 999

release:
  prerelease: auto
