FROM gcr.io/distroless/static-debian12:nonroot
ARG TARGETPLATFORM
USER 20000:20000
COPY --chmod=555 ${TARGETPLATFORM}/external-dns-poweradmin-webhook /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/external-dns-poweradmin-webhook"]
